"""Initial schema.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-05

This is revision one of a rebuilt schema. There is no prior migration history
and no `schema.sql` any more: `database/models.py` is the sole source of truth.

Rather than transcribing seventeen ``op.create_table`` calls that could silently
drift from the models, this revision creates the tables straight from
``Base.metadata``. Every *subsequent* revision is a normal autogenerated diff
against this baseline, so the usual granular upgrade/downgrade story starts from
revision two onward.

The pgvector extension is created first: ``curriculum_chunks.embedding`` is a
``vector`` column and its HNSW index needs the operator classes to exist.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from database.models import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
